<!DOCTYPE html>
<html lang="en"><head>
<script src="01-python-presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="01-python-presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="01-python-presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="01-python-presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="01-python-presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="01-python-presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="01-python-presentation_files/libs/quarto-html/quarto-syntax-highlighting-de070a7b0ab54f8780927367ac907214.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.30">

  <title>Intro to Statistical Programming in Python</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="01-python-presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="01-python-presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="01-python-presentation_files/libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link rel="stylesheet" href="styles.css">
  <link href="01-python-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="01-python-presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="01-python-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="01-python-presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Intro to Statistical Programming in Python</h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="playing-the-ballgame-early" class="slide level2">
<h2>Playing the ballgame early</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="mets-stadium.jpeg" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div><div class="column" style="width:50%;">
<p>You learn Python today by <em>doing</em> statistics: a junior version of the whole game, start to finish.</p>
<p><strong>What you will learn</strong></p>
<ul>
<li>read real data</li>
<li>compare two groups</li>
<li>test the difference</li>
<li>fit a regression</li>
</ul>
<p>Twenty-eight functions and methods, and that is the whole list.</p>
</div></div>
<div class="fragment">
<p>It is <strong>not</strong> a crash course in Python programming, or in hypothesis testing.</p>
</div>
</section>
<section id="todays-question" class="slide level2">
<h2>Today’s question</h2>
<blockquote>
<p><strong>Did states that expanded Medicaid in 2014 have lower working-age mortality than states that did not?</strong></p>
</blockquote>
</section>
<section id="todays-ballgame" class="slide level2">
<h2>Today’s Ballgame</h2>
<p><strong>Explore</strong>: What does mortality look like across states that expanded Medicaid and those that did not? &nbsp;&nbsp;→ <code>plt.hist()</code>, <code>.boxplot()</code>, group means</p>
<p><strong>Test</strong>: Is the difference in these states bigger than chance would produce? &nbsp;&nbsp;→ <code>stats.ttest_ind()</code></p>
<p><strong>Check</strong>: does the answer to our second question depend on unreasonable assumptions? &nbsp;&nbsp;→ permutation test</p>
<p><strong>Extend</strong>: how can we formally express and model these differences? &nbsp;&nbsp;→ <code>smf.ols("rate ~ expanded")</code></p>
</section>
<section id="how-today-works" class="slide level2">
<h2>How today works</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Module 1</strong></td>
<td>I do</td>
<td>I drive. You type every line with me.</td>
</tr>
<tr class="even">
<td><strong>Module 2</strong></td>
<td>We do</td>
<td>Pairs. Most of the code is given; you write the four that matter.</td>
</tr>
<tr class="odd">
<td><strong>Module 3</strong></td>
<td>You do</td>
<td>On your own. Nine steps, no code.</td>
</tr>
</tbody>
</table>
<p>The analysis is the <em>same shape</em> all three times. That is deliberate, because by the third pass, the shape is yours.</p>
</section>
<section id="two-rules" class="slide level2 scrollable">
<h2>Two rules</h2>
<ol type="1">
<li class="fragment"><p><strong>Type it, don’t read it.</strong> Type each code block into your script:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a><span class="co"># a comment: Python skips everything after a #</span></span>
<span id="cb1-2"><a href=""></a><span class="dv">2</span> <span class="op">+</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>4</code></pre>
</div>
</div>
<p>What prints underneath (<code>4</code>) is Python’s answer. Don’t type that.</p></li>
<li class="fragment"><p><strong>Errors are part of learning.</strong> I will make several on purpose. You will make more by accident. That never stops, for anyone.</p></li>
</ol>
<div class="fragment">
<p>Red sticky = stuck. Green = through. Put the red one up early.</p>
</div>
</section>
<section id="getting-in" class="slide level2 scrollable">
<h2>Getting in</h2>
<p>You set this up before today with <code>scripts/00-check.py</code>. Now:</p>
<ol type="1">
<li class="fragment"><strong>File → Open Folder</strong>, and choose the <code>intro-to-python</code> folder</li>
<li class="fragment">Click the Python version in the <strong>top-right corner</strong> and choose the one from this folder’s <code>.venv</code></li>
<li class="fragment">Open <code>scripts/01-i-do.py</code> and run a line with <strong>Cmd+Enter</strong> (Mac) / <strong>Ctrl+Enter</strong> (Windows)</li>
</ol>
<div class="fragment">
<p>Open the <strong>folder</strong>, not a file: it keeps every file path short. No <code>You're ready.</code> before today? Red sticky now.</p>
</div>
</section>
<section>
<section id="module-1-i-do" class="title-slide slide level1 center">
<h1>Module 1: I do</h1>

</section>
<section id="two-things-to-name-first" class="slide level2">
<h2>Two things to name first</h2>
<p>Every line today is built from two kinds of thing: <strong>objects</strong> and <strong>functions</strong>.</p>
<ul>
<li class="fragment">An <strong>object</strong> is something you made and gave a name to. It sits in the Variables pane until you overwrite it or restart Python.</li>
<li class="fragment">A <strong>function</strong> does something. You give it a name, a pair of parentheses, and whatever it needs to know inside them.</li>
</ul>
</section>
<section id="step-1-load-the-tools" class="slide level2">
<h2>Step 1: load the tools</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href=""></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-2"><a href=""></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-3"><a href=""></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-4"><a href=""></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb3-5"><a href=""></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Python on its own does not know about tables, plots, or statistics. Those live in <strong>libraries</strong>, and you load the ones you need at the top of every script.</p>
<div class="fragment">
<p><code>import pandas as pd</code> loads pandas under a short nickname: <code>pd.</code> means <em>the pandas version of</em>. Everyone uses these same five nicknames.</p>
</div>
</section>
<section id="anatomy-of-a-function-call" class="slide level2">
<h2>Anatomy of a function call</h2>
<div class="anatomy big">
<p><span class="fragment highlight-current-red" data-fragment-index="1">pd.</span><span class="fragment highlight-current-red" data-fragment-index="2">read_csv</span><span class="fragment highlight-current-red" data-fragment-index="3">(</span><span class="fragment highlight-current-red" data-fragment-index="4">"data/medicaid.csv"</span><span class="fragment highlight-current-red" data-fragment-index="6">,&nbsp;</span><span class="fragment highlight-current-red" data-fragment-index="5">index_col=0</span><span class="fragment highlight-current-red" data-fragment-index="3">)</span></p>
</div>
<div class="fragment" data-fragment-index="1">
<p><strong><code>pd.</code></strong> says where the function lives: in pandas, the table library, which we just loaded under the short name <code>pd</code>.</p>
</div>
<div class="fragment" data-fragment-index="2">
<p><strong><code>read_csv</code></strong> is the function name. It says what you want done.</p>
</div>
<div class="fragment" data-fragment-index="3">
<p><strong><code>( )</code></strong> holds everything the function needs to know.</p>
</div>
<div class="fragment" data-fragment-index="4">
<p><strong><code>"data/medicaid.csv"</code></strong> is the first argument: which file to read.</p>
</div>
<div class="fragment" data-fragment-index="5">
<p><strong><code>index_col=0</code></strong> is a named argument: treat the first column as row labels, not data. (Python counts from 0, so column 0 <em>is</em> the first.)</p>
</div>
<div class="fragment" data-fragment-index="6">
<p><strong><code>,</code></strong> separates one argument from the next.</p>
</div>
<div class="fragment" data-fragment-index="7">
<p>Two questions get you through any function: <strong>what do I want Python to do</strong>, and <strong>what does Python need to know to do it?</strong></p>
</div>
</section>
<section id="step-2-read-the-data" class="slide level2">
<h2>Step 2: read the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href=""></a>counties <span class="op">=</span> pd.read_csv(<span class="st">"data/medicaid.csv"</span>, index_col<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nothing printed. That is what success looks like: <code>=</code> stores silently.</p>
<div class="fragment">
<p>Look at the <strong>Variables</strong> pane. <code>counties</code> is now in it.</p>
</div>
</section>
<section id="step-2-three-questions" class="slide level2">
<h2>Step 2: three questions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href=""></a>counties.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(26066, 13)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href=""></a>counties.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index(['state', 'county', 'county_code', 'year', 'population_20_64', 'yaca',
       'perc_white', 'perc_hispanic', 'perc_female', 'crude_rate_20_64',
       'unemp_rate', 'poverty_rate', 'median_income'],
      dtype='str')</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href=""></a>counties.head(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  state              county  county_code  year  population_20_64  yaca  \
1    AL  Autauga County, AL         1001  2009             31271   NaN   
2    AL  Autauga County, AL         1001  2010             31875   NaN   
3    AL  Autauga County, AL         1001  2011             32538   NaN   

   perc_white  perc_hispanic  perc_female  crude_rate_20_64  unemp_rate  \
1   80.429152       2.078603    51.482204        412.522785    8.905110   
2   80.445490       2.240000    51.381961        423.529412    8.808109   
3   79.568505       2.311144    51.146352        482.512754    8.345908   

   poverty_rate  median_income  
1          11.2         53.081  
2          11.9         53.049  
3          14.9         48.863  </code></pre>
</div>
</div>
<p>Ask these of every new dataset: <strong>how big, what columns, what’s a row.</strong></p>
<div class="fragment">
<p>The dot means <em>belonging to</em>: <code>counties.shape</code> is the shape of <code>counties</code>. With parentheses, <code>.head(3)</code> <strong>does</strong> something; it is a <em>method</em>. Without them, <code>.shape</code> just <strong>looks something up</strong>; it is an <em>attribute</em>.</p>
</div>
</section>
<section id="step-3-look-at-the-outcome" class="slide level2">
<h2>Step 3: look at the outcome</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href=""></a>plt.figure()</span>
<span id="cb11-2"><a href=""></a>plt.hist(counties[<span class="st">"crude_rate_20_64"</span>])</span>
<span id="cb11-3"><a href=""></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="01-python-presentation_files/figure-revealjs/unnamed-chunk-9-1.png" class="quarto-figure quarto-figure-center r-stretch"><p>Never test a variable you have not looked at. Defaults are fine; we are not decorating anything yet.</p>
<div class="fragment">
<p><code>plt.figure()</code> starts a fresh picture and <code>plt.show()</code> shows it. Skip <code>plt.figure()</code> and your next plot lands on top of this one.</p>
</div>
</section>
<section id="what-are-those" class="slide level2">
<h2>What are those <code>[" "]</code>?</h2>
<div style="font-size: 1.3em; text-align: center; margin: 0.6em 0;">
<p><code>plt.hist(counties</code><span class="pop"><code>["</code></span><code>crude_rate_20_64</code><span class="pop"><code>"]</code></span><code>)</code></p>
</div>
<p>You have not seen square brackets used like that before. <strong>Don’t look it up yet.</strong></p>
<div class="fragment">
<p>Use what is already on the screen:</p>
</div>
<ul>
<li class="fragment"><code>counties</code> is the table you just read in</li>
<li class="fragment"><code>"crude_rate_20_64"</code> was in the list <code>.columns</code> printed</li>
<li class="fragment">so <code>[" "]</code> has to pick <strong>one of its columns</strong> out of <strong>a table</strong></li>
</ul>
<div class="fragment">
<p><strong>Use the context clues.</strong> Read around the unfamiliar piece first, guess what it has to be, then check. Faster than looking it up cold, and it sticks.</p>
</div>
</section>
<section id="reading-from-the-inside-out" class="slide level2 scrollable">
<h2>Reading from the inside out</h2>
<p><code>plt.hist(counties["crude_rate_20_64"])</code> has two steps, and the inner one happens first.</p>
<ol type="1">
<li class="fragment"><code>counties["crude_rate_20_64"]</code> pulls the column out. On its own it is a Series: one number per county.</li>
<li class="fragment"><code>plt.hist()</code> draws that Series.</li>
</ol>
<div class="fragment">
<blockquote>
<p>“Take the <code>crude_rate_20_64</code> column out of <code>counties</code>, and draw a histogram of it.”</p>
</blockquote>
</div>
</section>
<section id="step-4-get-the-data-ready" class="slide level2">
<h2>Step 4: get the data ready</h2>
<blockquote>
<p><strong>Did states that expanded Medicaid in 2014 have lower working-age mortality than states that did not?</strong></p>
</blockquote>
<p>What do we need to do to our data before we can answer that?</p>
<div class="fragment">
<p><strong>1. Aggregate.</strong> Expansion is a <em>state</em> policy, so we need one mortality rate per state, for 2014.</p>
</div>
<div class="fragment">
<p><strong>2. Deal with the NAs.</strong> How is the policy recorded right now?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href=""></a>counties[<span class="st">"yaca"</span>].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: yaca, dtype: float64</code></pre>
</div>
</div>
<p><code>yaca</code> is the year a state expanded; <code>NaN</code> (missing) means never. We need a clean 1 or 0.</p>
</div>
<div class="fragment">
<p><strong>3. Weight by population.</strong> The smallest and largest counties in 2014:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                       people aged 20-64  deaths % who died
county                                                     
Arthur County, NE                    224       0     0.000%
Los Angeles County, CA         6,298,815  15,397     0.244%</code></pre>
</div>
</div>
<p>Averaging county rates gives these two the same vote. <strong>Is that a reasonable comparison?</strong></p>
</div>
<aside class="notes">
<p>Take answers for each before revealing the next. On 3: one death in Arthur County would put it at 0.446%, nearly twice Los Angeles. The three names are the plan for the next several slides: aggregate, deal with the NAs, weight by population. We take them in the order the code needs them: keep 2014, label the states, then add up deaths and people by state.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-4a-keep-one-year" class="slide level2">
<h2>Step 4a: keep one year</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href=""></a>d2014 <span class="op">=</span> counties[counties[<span class="st">"year"</span>] <span class="op">==</span> <span class="dv">2014</span>]</span>
<span id="cb15-2"><a href=""></a>d2014.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(2372, 13)</code></pre>
</div>
</div>
<div class="fragment">
<p>Square brackets with a <code>True</code>/<code>False</code> test inside keep the rows where the test is <code>True</code>. <code>==</code> asks <em>is this equal to?</em>: a question, so it is doubled.</p>
</div>
</section>
<section id="reading-a-line-right-to-left" class="slide level2">
<h2>Reading a line, right to left</h2>
<div style="font-size: 1.05em; text-align: center; margin: 0.5em 0;">
<p><code>d2014 = counties[counties["year"] == 2014]</code></p>
</div>
<p>Longer lines are still one sentence. Start at the right:</p>
<ul>
<li class="fragment"><code>counties[counties["year"] == 2014]</code> says <em>from <code>counties</code>, keep the rows where <code>year</code> is 2014</em> …</li>
<li class="fragment"><code>=</code> says <em>… and store it</em> …</li>
<li class="fragment"><code>d2014</code> says <em>… as <code>d2014</code>.</em></li>
</ul>
<div class="fragment">
<blockquote>
<p>“<strong>From <code>counties</code>, keep the rows where <code>year</code> is 2014, and store that as <code>d2014</code>.</strong>”</p>
</blockquote>
</div>
<div class="fragment">
<p>If you can say a line out loud, you understand it. If you cannot, stop and ask.</p>
</div>
</section>
<section id="step-4b-label-each-state" class="slide level2">
<h2>Step 4b: label each state</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href=""></a>d2014[<span class="st">"expanded"</span>] <span class="op">=</span> np.where(d2014[<span class="st">"yaca"</span>].notna() <span class="op">&amp;</span> (d2014[<span class="st">"yaca"</span>] <span class="op">==</span> <span class="dv">2014</span>), <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb17-2"><a href=""></a>d2014[<span class="st">"expanded"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>expanded
0    1337
1    1035
Name: count, dtype: int64</code></pre>
</div>
</div>
<p><code>np.where(test, value_if_true, value_if_false)</code> runs down the whole column.</p>
<div class="fragment">
<p>Note the square brackets doing a second job: on the <strong>left</strong> of <code>=</code> they create a column rather than pulling one out.</p>
</div>
</section>
<section id="why-the-.notna-guard" class="slide level2">
<h2>Why the <code>.notna()</code> guard</h2>
<p>A missing value answers <code>False</code> to <em>every</em> comparison, so <code>NaN == 2014</code> quietly lands in the 0 group. The guard says so out loud: <em>not missing, and equal to 2014.</em></p>
<div class="fragment">
<p>The trap: Python does <code>&amp;</code> <strong>before</strong> <code>==</code>. Drop the parentheses and there is no error:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href=""></a>np.where(d2014[<span class="st">"yaca"</span>].notna() <span class="op">&amp;</span> d2014[<span class="st">"yaca"</span>] <span class="op">==</span> <span class="dv">2014</span>, <span class="dv">1</span>, <span class="dv">0</span>).<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.int64(0)</code></pre>
</div>
</div>
<p>Every county lands in “did not expand”. Silent wrong answers are worse than errors.</p>
</div>
</section>
<section id="ask-python-itself" class="slide level2">
<h2>Ask Python itself</h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href=""></a><span class="bu">help</span>(pd.Series.mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <strong>Help</strong> pane lists every argument and its default: <code>Series.mean(*, axis=0, skipna=True, ...)</code>. So pandas skips missing values unless you say otherwise.</p>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href=""></a>counties[<span class="st">"median_income"</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(47.093609535142605)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href=""></a>counties[<span class="st">"median_income"</span>].mean(skipna<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(nan)</code></pre>
</div>
</div>
<p>Fifteen rows are missing an income, and the first answer left them out without a word. When a result looks off, <code>help()</code> the function and check its defaults.</p>
</div>
<aside class="notes">
<p>Before the fragment, ask the room: how many arguments does <code>.mean()</code> take, what does <code>skipna</code> do (scroll to Parameters), and what is it set to if you don’t say? <code>.isna().sum()</code> counts what was skipped.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-template-y-broken-down-by-x" class="slide level2">
<h2>The template: <em>y</em> broken down by <em>x</em></h2>
<p>One pattern does most of the work today.</p>
<div style="font-size: 1.5em; text-align: center; margin: 0.5em 0;">
<p><code>data.groupby(x)[y].goal()</code></p>
</div>
<p>Read <code>groupby(x)</code>, <code>by=x</code>, and <code>~ x</code> as <strong>“broken down by”</strong>.</p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>states.groupby("expanded")["rate"].mean()</code></td>
<td>group means</td>
</tr>
<tr class="even">
<td><code>states.boxplot(column="rate", by="expanded")</code></td>
<td>a picture</td>
</tr>
<tr class="odd">
<td><code>smf.ols("rate ~ expanded", data=states)</code></td>
<td>a model</td>
</tr>
</tbody>
</table>
<p>The t-test is the odd one out: it wants the two groups handed over one at a time.</p>
</section>
<section id="step-4c-weight-by-population" class="slide level2">
<h2>Step 4c: weight by population</h2>
<p>A rate is deaths over people. To get a state’s rate, turn each county’s rate back into deaths, add up the deaths and the people by state, and divide once.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href=""></a>d2014[<span class="st">"deaths"</span>] <span class="op">=</span> d2014[<span class="st">"crude_rate_20_64"</span>] <span class="op">*</span> d2014[<span class="st">"population_20_64"</span>] <span class="op">/</span> <span class="fl">1e5</span></span>
<span id="cb26-2"><a href=""></a></span>
<span id="cb26-3"><a href=""></a>states <span class="op">=</span> d2014.groupby([<span class="st">"state"</span>, <span class="st">"expanded"</span>],</span>
<span id="cb26-4"><a href=""></a>                       as_index<span class="op">=</span><span class="va">False</span>)[[<span class="st">"deaths"</span>, <span class="st">"population_20_64"</span>]].<span class="bu">sum</span>()</span>
<span id="cb26-5"><a href=""></a>states[<span class="st">"crude_rate_20_64"</span>] <span class="op">=</span> states[<span class="st">"deaths"</span>] <span class="op">/</span> states[<span class="st">"population_20_64"</span>] <span class="op">*</span> <span class="fl">1e5</span></span>
<span id="cb26-6"><a href=""></a>states <span class="op">=</span> states.sort_values(<span class="st">"state"</span>)</span>
<span id="cb26-7"><a href=""></a>states.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(39, 5)</code></pre>
</div>
</div>
<div class="fragment">
<p>The template again: <code>d2014.groupby(x)[y].sum()</code>, where <em>x</em> is state and expansion status and <em>y</em> is deaths and population. Two of each, so both go in a <strong>list</strong>, <code>[ ]</code>.</p>
</div>
<div class="fragment">
<p>Sorting changes nothing today, but the shuffling in step 7 depends on row order. Make the order a decision you can see.</p>
</div>
<aside class="notes">
<p><code>as_index=False</code> keeps state and expanded as ordinary columns, so we get a plain table. Leave the parentheses off <code>.sum</code> and Python prints <code>&lt;bound method ...&gt;</code> instead of an answer.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="i-read-these" class="slide level2">
<h2>I read these</h2>
<div class="readrow fragment" data-fragment-index="1">
<div class="columns">
<div class="column" style="width:45%;">
<p><code>plt.hist(counties["crude_rate_20_64"])</code></p>
</div><div class="column" style="width:55%;">
<p>“Take the <code>crude_rate_20_64</code> column out of <code>counties</code>, and draw a histogram of it.”</p>
</div></div>
</div>
<div class="readrow fragment" data-fragment-index="2">
<div class="columns">
<div class="column" style="width:45%;">
<p><code>d2014 = counties[counties["year"] == 2014]</code></p>
</div><div class="column" style="width:55%;">
<p>“From <code>counties</code>, keep the rows where <code>year</code> is 2014, and store that as <code>d2014</code>.”</p>
</div></div>
</div>
<div class="readrow fragment" data-fragment-index="3">
<div class="columns">
<div class="column" style="width:45%;">
<p><code>d2014.groupby("state")["population_20_64"].sum()</code></p>
</div><div class="column" style="width:55%;">
<p>“Using <code>d2014</code>, add up <code>population_20_64</code> broken down by <code>state</code>.”</p>
</div></div>
</div>
<div class="readrow fragment" data-fragment-index="4">
<div class="columns">
<div class="column" style="width:45%;">
<p><code>d2014["deaths"] = d2014["crude_rate_20_64"] * d2014["population_20_64"] / 1e5</code></p>
</div><div class="column" style="width:55%;">
<p>“Multiply each county’s rate by its population, divide by 100,000, and store the result as a new column called <code>deaths</code>.”</p>
</div></div>
</div>
</section>
<section id="now-you-read-these" class="slide level2">
<h2>Now you read these</h2>
<div class="readrow">
<div class="columns">
<div class="column" style="width:45%;">
<p><span class="fragment" data-fragment-index="1"><code>states["expanded"].value_counts()</code></span></p>
</div><div class="column" style="width:55%;">
<p><span class="fragment" data-fragment-index="2">&nbsp;“Take the <code>expanded</code> column out of <code>states</code>, and count how many of each value there are.”</span></p>
</div></div>
</div>
<div class="readrow">
<div class="columns">
<div class="column" style="width:45%;">
<p><span class="fragment" data-fragment-index="3"><code>high_pov = states[states["poverty_rate"] &gt; 20]</code></span></p>
</div><div class="column" style="width:55%;">
<p><span class="fragment" data-fragment-index="4">&nbsp;“From <code>states</code>, keep the rows where <code>poverty_rate</code> is above 20, and store that as <code>high_pov</code>.”</span></p>
</div></div>
</div>
<div class="readrow">
<div class="columns">
<div class="column" style="width:45%;">
<p><span class="fragment" data-fragment-index="5"><code>states.groupby("expanded")["poverty_rate"].mean()</code></span></p>
</div><div class="column" style="width:55%;">
<p><span class="fragment" data-fragment-index="6">&nbsp;“Using <code>states</code>, average <code>poverty_rate</code> broken down by <code>expanded</code>.”</span></p>
</div></div>
</div>
<div class="readrow">
<div class="columns">
<div class="column" style="width:45%;">
<p><span class="fragment" data-fragment-index="7"><code>states["big"] = np.where(states["poverty_rate"] &gt; 20, 1, 0)</code></span></p>
</div><div class="column" style="width:55%;">
<p><span class="fragment" data-fragment-index="8">&nbsp;“Test whether each state’s <code>poverty_rate</code> is above 20, give it 1 if yes and 0 if no, and store that as a new column called <code>big</code>.”</span></p>
</div></div>
</div>
<aside class="notes">
<p>Reveal the code, take an answer from the room, then reveal the wording. Each one mirrors the example directly above it on the previous slide.</p>
<p>The wording does not have to match mine; the structure does. Listen for whether they start at the right and work back, and whether they say “store it as” for the <code>=</code>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="describe-step-5-look-at-the-comparison" class="slide level2">
<h2>DESCRIBE · Step 5: look at the comparison</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href=""></a>states.boxplot(column<span class="op">=</span><span class="st">"crude_rate_20_64"</span>, by<span class="op">=</span><span class="st">"expanded"</span>)</span>
<span id="cb28-2"><a href=""></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="01-python-presentation_files/figure-revealjs/unnamed-chunk-17-3.png" class="quarto-figure quarto-figure-center r-stretch"><div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href=""></a>states.groupby(<span class="st">"expanded"</span>)[<span class="st">"crude_rate_20_64"</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>expanded
0    390.166064
1    350.988408
Name: crude_rate_20_64, dtype: float64</code></pre>
</div>
</div>
<p><code>.boxplot()</code> starts its own fresh picture, so no <code>plt.figure()</code> this time.</p>
</section>
<section id="describe-step-5-the-estimate-as-one-number" class="slide level2">
<h2>DESCRIBE · Step 5: the estimate, as one number</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href=""></a>group_means <span class="op">=</span> states.groupby(<span class="st">"expanded"</span>)[<span class="st">"crude_rate_20_64"</span>].mean()</span>
<span id="cb31-2"><a href=""></a>diff_obs <span class="op">=</span> group_means[<span class="dv">1</span>] <span class="op">-</span> group_means[<span class="dv">0</span>]</span>
<span id="cb31-3"><a href=""></a>diff_obs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(-39.177656336384814)</code></pre>
</div>
</div>
<p>Expansion states averaged about <strong>39 fewer deaths per 100,000</strong> working-age people.</p>
<p>Is that more than luck would hand us?</p>
<div class="fragment">
<p><code>group_means[1]</code> is the row <em>labelled</em> 1: the expanded states. <code>np.float64(...)</code> is numpy saying what <em>kind</em> of number this is. The number is the part inside.</p>
</div>
</section>
<section id="test-step-6-the-test-you-already-know" class="slide level2">
<h2>TEST · Step 6: the test you already know</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href=""></a>result <span class="op">=</span> stats.ttest_ind(states[<span class="st">"crude_rate_20_64"</span>][states[<span class="st">"expanded"</span>] <span class="op">==</span> <span class="dv">1</span>],</span>
<span id="cb33-2"><a href=""></a>                         states[<span class="st">"crude_rate_20_64"</span>][states[<span class="st">"expanded"</span>] <span class="op">==</span> <span class="dv">0</span>],</span>
<span id="cb33-3"><a href=""></a>                         equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb33-4"><a href=""></a>result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>TtestResult(statistic=np.float64(-1.5434721815517884), pvalue=np.float64(0.13180569962554284), df=np.float64(34.632273771767))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href=""></a>result.confidence_interval()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ConfidenceInterval(low=np.float64(-90.72705983416654), high=np.float64(12.371747161396911))</code></pre>
</div>
</div>
<p>Read all of it. The <strong>interval</strong> tells you the size of the gap the data supports. The p-value never does.</p>
<div class="fragment">
<p><code>equal_var=False</code> asks for Welch’s t-test, which does not assume the two groups are equally spread out.</p>
</div>
</section>
<section id="which-way-round" class="slide level2">
<h2>Which way round?</h2>
<p>We computed <code>diff_obs = −39</code>. The interval says <strong>−91 to +12</strong>. Same sign.</p>
<div class="fragment">
<p><code>ttest_ind(a, b)</code> subtracts <strong>a − b</strong>, and we handed it the expanded states first: <strong>group 1 − group 0</strong>, the same way round as <code>diff_obs</code>.</p>
</div>
<div class="fragment">
<p>Swap them and every sign flips, with no warning. When a sign looks wrong, check which way round the subtraction went.</p>
</div>
</section>
<section id="check-step-7-what-does-p-0.13-actually-mean" class="slide level2">
<h2>CHECK · Step 7: what does p = 0.13 actually mean?</h2>
<p>Most of us walk in carrying this one:</p>
<blockquote>
<p><del>“p is the probability the result is due to chance.”</del></p>
</blockquote>
<div class="fragment">
<p>It has the logic <strong>backwards</strong>.</p>
</div>
<div class="fragment">
<p>It <strong>assumes chance is all there is</strong>, and then asks:</p>
<blockquote>
<p>if expansion made no difference at all, how often would luck alone hand us a gap as big as ours?</p>
</blockquote>
</div>
</section>
<section id="check-step-7-so-lets-build-one" class="slide level2">
<h2>CHECK · Step 7: so let’s build one</h2>
<ul>
<li class="fragment">The null hypothesis says the labels are meaningless.</li>
<li class="fragment">So let’s <em>make</em> them meaningless by shuffling which states expanded.</li>
<li class="fragment">Do that a thousand times, and we have a thousand worlds where the policy did nothing.</li>
<li class="fragment">Then just count how many of them beat our real result.</li>
</ul>
<div class="fragment">
<p>We don’t have to trust a formula for this. <strong>We can just do it.</strong></p>
</div>
</section>
<section id="step-7-one-fake-world" class="slide level2">
<h2>Step 7: one fake world</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href=""></a>rng <span class="op">=</span> np.random.default_rng()</span>
<span id="cb37-2"><a href=""></a>shuffled <span class="op">=</span> rng.permutation(states[<span class="st">"expanded"</span>])</span>
<span id="cb37-3"><a href=""></a></span>
<span id="cb37-4"><a href=""></a>(states[<span class="st">"crude_rate_20_64"</span>][shuffled <span class="op">==</span> <span class="dv">1</span>].mean() <span class="op">-</span></span>
<span id="cb37-5"><a href=""></a> states[<span class="st">"crude_rate_20_64"</span>][shuffled <span class="op">==</span> <span class="dv">0</span>].mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(-37.74574697362232)</code></pre>
</div>
</div>
<p><code>rng</code> is a random number generator: the thing that does the shuffling. Run it again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href=""></a>shuffled <span class="op">=</span> rng.permutation(states[<span class="st">"expanded"</span>])</span>
<span id="cb39-2"><a href=""></a>(states[<span class="st">"crude_rate_20_64"</span>][shuffled <span class="op">==</span> <span class="dv">1</span>].mean() <span class="op">-</span></span>
<span id="cb39-3"><a href=""></a> states[<span class="st">"crude_rate_20_64"</span>][shuffled <span class="op">==</span> <span class="dv">0</span>].mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(-9.621431079807053)</code></pre>
</div>
</div>
<p>That bouncing <strong>is</strong> sampling variation. You are looking straight at it.</p>
</section>
<section id="step-7-a-thousand-fake-worlds" class="slide level2">
<h2>Step 7: a thousand fake worlds</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href=""></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">2026</span>)</span>
<span id="cb41-2"><a href=""></a>diffs <span class="op">=</span> []</span>
<span id="cb41-3"><a href=""></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1000</span>):</span>
<span id="cb41-4"><a href=""></a>    shuffled <span class="op">=</span> rng.permutation(states[<span class="st">"expanded"</span>])</span>
<span id="cb41-5"><a href=""></a>    diffs.append(states[<span class="st">"crude_rate_20_64"</span>][shuffled <span class="op">==</span> <span class="dv">1</span>].mean() <span class="op">-</span></span>
<span id="cb41-6"><a href=""></a>                 states[<span class="st">"crude_rate_20_64"</span>][shuffled <span class="op">==</span> <span class="dv">0</span>].mean())</span>
<span id="cb41-7"><a href=""></a>diffs <span class="op">=</span> np.array(diffs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The seed, <code>2026</code>, makes the shuffling repeatable. <code>for i in range(1000):</code> runs the indented lines 1000 times; <code>.append()</code> keeps each answer. The indent <em>is</em> the grouping, so line it up exactly.</p>
</section>
<section id="step-7-and-there-it-is" class="slide level2">
<h2>Step 7: and there it is</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href=""></a>plt.figure()</span>
<span id="cb42-2"><a href=""></a>plt.hist(diffs)</span>
<span id="cb42-3"><a href=""></a>plt.axvline(diff_obs, color<span class="op">=</span><span class="st">"red"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb42-4"><a href=""></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="01-python-presentation_files/figure-revealjs/unnamed-chunk-24-5.png" class="quarto-figure quarto-figure-center r-stretch"><div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href=""></a>(<span class="bu">abs</span>(diffs) <span class="op">&gt;=</span> <span class="bu">abs</span>(diff_obs)).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(0.131)</code></pre>
</div>
</div>
<p>A p-value you built out of shuffling and counting.</p>
<div class="fragment">
<p>The t-test said 0.132. Not identical, and it shouldn’t be: 1000 shuffles is itself a sample. Same conclusion: not distinguishable from chance with 39 states.</p>
</div>
</section>
<section id="that-one-line-does-three-things" class="slide level2">
<h2>That one line does three things</h2>
<div class="sourceCode" id="cb45"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href=""></a>( <span class="bu">abs</span>(diffs) <span class="op">&gt;=</span> <span class="bu">abs</span>(diff_obs) ).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><code>abs()</code></td>
<td>drops the minus sign, so we count both tails: past −39 and past +39. That is what “two-sided” means, and it is what <code>ttest_ind()</code> did.</td>
</tr>
<tr class="even">
<td><code>&gt;=</code></td>
<td>gives a <code>True</code>/<code>False</code> for each of the 1000 shuffles</td>
</tr>
<tr class="odd">
<td><code>.mean()</code></td>
<td>of <code>True</code>/<code>False</code> gives the proportion that are <code>True</code>, because <code>True</code> counts as 1</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Drop the <code>abs()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href=""></a>(diffs <span class="op">&gt;=</span> diff_obs).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(0.915)</code></pre>
</div>
</div>
<p>Our difference is negative, so this counts almost every shuffle. No warning, just a wrong number.</p>
</div>
</section>
<section id="model-step-8-the-same-answer-as-a-regression" class="slide level2">
<h2>MODEL · Step 8: the same answer, as a regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href=""></a>m <span class="op">=</span> smf.ols(<span class="st">"crude_rate_20_64 ~ expanded"</span>, data<span class="op">=</span>states).fit()</span>
<span id="cb48-2"><a href=""></a><span class="bu">print</span>(m.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:       crude_rate_20_64   R-squared:                       0.060
Model:                            OLS   Adj. R-squared:                  0.035
Method:                 Least Squares   F-statistic:                     2.380
Date:                Tue, 29 Sep 2026   Prob (F-statistic):              0.131
Time:                        12:55:18   Log-Likelihood:                -224.55
No. Observations:                  39   AIC:                             453.1
Df Residuals:                      37   BIC:                             456.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    390.1661     19.075     20.454      0.000     351.516     428.816
expanded     -39.1777     25.397     -1.543      0.131     -90.637      12.282
==============================================================================
Omnibus:                        4.688   Durbin-Watson:                   1.769
Prob(Omnibus):                  0.096   Jarque-Bera (JB):                4.369
Skew:                           0.809   Prob(JB):                        0.113
Kurtosis:                       2.738   Cond. No.                         2.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><code>smf.ols()</code> sets the model up, outcome <code>~</code> predictor. <code>.fit()</code> fits it. <code>print()</code> lays the table out.</p>
</section>
<section id="model-step-8-you-need-two-numbers-from-that" class="slide level2">
<h2>MODEL · Step 8: you need two numbers from that</h2>
<p>Both on the <strong><code>expanded</code></strong> row:</p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>coef</code></td>
<td><strong>−39.18</strong></td>
<td>our difference in means, exactly</td>
</tr>
<tr class="even">
<td><code>P&gt;|t|</code></td>
<td><strong>0.131</strong></td>
<td>our p-value</td>
</tr>
</tbody>
</table>
<p><code>Intercept</code>, on the row above, is the mean of the group coded 0: the baseline. Everything else answers questions we haven’t asked.</p>
<div class="fragment">
<p>A difference in means <em>is</em> a regression coefficient. t-test, permutation test, and regression: three ways of asking one question, and they agree.</p>
</div>
<aside class="notes">
<p><code>equal_var=False</code> is Welch’s correction, which is why the t-test’s df was 34.63 rather than 37. <code>equal_var=True</code> matches <code>ols()</code> to the decimal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-9-why-we-used-39-rows-and-not-2372" class="slide level2">
<h2>Step 9: why we used 39 rows and not 2,372</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href=""></a>stats.ttest_ind(d2014[<span class="st">"crude_rate_20_64"</span>][d2014[<span class="st">"expanded"</span>] <span class="op">==</span> <span class="dv">1</span>],</span>
<span id="cb50-2"><a href=""></a>                d2014[<span class="st">"crude_rate_20_64"</span>][d2014[<span class="st">"expanded"</span>] <span class="op">==</span> <span class="dv">0</span>],</span>
<span id="cb50-3"><a href=""></a>                equal_var<span class="op">=</span><span class="va">False</span>).pvalue</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(5.687913728799441e-17)</code></pre>
</div>
</div>
<p>That is the same test, run on the counties.</p>
<div class="fragment">
<p><code>p</code> is about 6e-17. Overwhelming, and wrong.</p>
</div>
<div class="fragment">
<p>It thinks it has 2,372 independent observations. It has 39: every county in a state shares one policy decision.</p>
</div>
<div class="fragment">
<p>When a p-value looks too good, ask how many independent things you actually measured.</p>
</div>
</section>
<section id="that-was-the-whole-game" class="slide level2">
<h2>That was the whole game</h2>
<div style="font-size: 0.8em;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>What you did</th>
<th>With</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1–2</td>
<td>Load tools, read the data</td>
<td><code>pd.read_csv()</code> <code>.head()</code></td>
</tr>
<tr class="even">
<td>3</td>
<td>Look at the outcome</td>
<td><code>plt.figure()</code> <code>plt.hist()</code> <code>plt.show()</code></td>
</tr>
<tr class="odd">
<td>4</td>
<td>Get the data ready</td>
<td><code>np.where()</code> <code>.notna()</code> <code>.isna()</code> <code>.value_counts()</code> <code>.groupby()</code> <code>.sum()</code> <code>.sort_values()</code></td>
</tr>
<tr class="even">
<td>5</td>
<td>Describe</td>
<td><code>.boxplot()</code> <code>.mean()</code></td>
</tr>
<tr class="odd">
<td>6</td>
<td>Test</td>
<td><code>stats.ttest_ind()</code> <code>.confidence_interval()</code></td>
</tr>
<tr class="even">
<td>7</td>
<td>Check</td>
<td><code>np.random.default_rng()</code> <code>.permutation()</code> <code>range()</code> <code>.append()</code> <code>np.array()</code> <code>plt.axvline()</code> <code>abs()</code></td>
</tr>
<tr class="odd">
<td>8</td>
<td>Model</td>
<td><code>smf.ols()</code> <code>.fit()</code> <code>.summary()</code> <code>print()</code></td>
</tr>
<tr class="even">
<td>Module 2</td>
<td>Split at the median</td>
<td><code>.median()</code></td>
</tr>
</tbody>
</table>
</div>
<p>Twenty-eight functions and methods: a difference in means, a permutation test, and a regression, plus the reason to distrust one of them.</p>
</section>
<section id="glossary-the-twenty-eight-functions-and-methods" class="slide level2">
<h2>Glossary: the twenty-eight functions and methods</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div style="font-size: 0.52em;">
<p><strong>Get data, look at it</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>pd.read_csv()</code></td>
<td>read a spreadsheet off disk</td>
</tr>
<tr class="even">
<td><code>.head()</code></td>
<td>show the first few rows</td>
</tr>
</tbody>
</table>
<p><strong>Pictures</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>plt.figure()</code></td>
<td>start a fresh, blank picture</td>
</tr>
<tr class="even">
<td><code>plt.hist()</code></td>
<td>distribution of one variable</td>
</tr>
<tr class="odd">
<td><code>.boxplot()</code></td>
<td>compare groups</td>
</tr>
<tr class="even">
<td><code>plt.axvline()</code></td>
<td>add a vertical line to the picture</td>
</tr>
<tr class="odd">
<td><code>plt.show()</code></td>
<td>show the picture</td>
</tr>
</tbody>
</table>
<p><strong>Build a grouping variable</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>np.where()</code></td>
<td>test each value, return 1 or 0</td>
</tr>
<tr class="even">
<td><code>.notna()</code> / <code>.isna()</code></td>
<td>is this value present / missing?</td>
</tr>
<tr class="odd">
<td><code>.value_counts()</code></td>
<td>count how many in each category</td>
</tr>
</tbody>
</table>
<p><strong>Summarise</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>.groupby()</code></td>
<td>split a table by group; what follows runs on each</td>
</tr>
<tr class="even">
<td><code>.mean()</code></td>
<td>average, and on True/False a proportion</td>
</tr>
<tr class="odd">
<td><code>.sum()</code></td>
<td>add up</td>
</tr>
<tr class="even">
<td><code>.median()</code></td>
<td>the middle value</td>
</tr>
<tr class="odd">
<td><code>abs()</code></td>
<td>drop the minus sign</td>
</tr>
<tr class="even">
<td><code>.sort_values()</code></td>
<td>sort the rows by a column</td>
</tr>
</tbody>
</table>
</div>
</div><div class="column" style="width:50%;">
<div style="font-size: 0.52em;">
<p><strong>Test and model</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>stats.ttest_ind()</code></td>
<td>compare two group means</td>
</tr>
<tr class="even">
<td><code>.confidence_interval()</code></td>
<td>the interval for that difference</td>
</tr>
<tr class="odd">
<td><code>smf.ols()</code></td>
<td>set up a linear model, <code>y ~ x</code></td>
</tr>
<tr class="even">
<td><code>.fit()</code></td>
<td>fit it</td>
</tr>
<tr class="odd">
<td><code>.summary()</code></td>
<td>the model’s coefficient table</td>
</tr>
<tr class="even">
<td><code>print()</code></td>
<td>lay that table out properly</td>
</tr>
</tbody>
</table>
<p><strong>The permutation test</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><code>np.random.default_rng()</code></td>
<td>a random number generator; give it a seed to repeat it</td>
</tr>
<tr class="even">
<td><code>.permutation()</code></td>
<td>shuffle into a random order</td>
</tr>
<tr class="odd">
<td><code>range()</code></td>
<td>the numbers 0 to n − 1, for a loop to count through</td>
</tr>
<tr class="even">
<td><code>.append()</code></td>
<td>add an answer to the end of a list</td>
</tr>
<tr class="odd">
<td><code>np.array()</code></td>
<td>turn a list into an array, so maths works on all of it</td>
</tr>
</tbody>
</table>
<p><strong>Look something up</strong> (attributes: no parentheses)</p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>.shape</code></td>
<td>how many rows and columns</td>
</tr>
<tr class="even">
<td><code>.columns</code></td>
<td>what are the columns called</td>
</tr>
<tr class="odd">
<td><code>.pvalue</code></td>
<td>just the p-value from a test</td>
</tr>
</tbody>
</table>
</div>
<div style="font-size: 0.72em; margin-top: 0.5em;">
<p>Three more appear only in the finish-early extensions: <code>plt.scatter()</code>, <code>plt.axline()</code>, and the <code>.params</code> attribute. And <code>help()</code> works on all of them.</p>
</div>
</div></div>
</section>
<section id="glossary-the-symbols" class="slide level2">
<h2>Glossary: the symbols</h2>
<div style="font-size: 0.6em;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td><code>#</code></td>
<td>everything after it is ignored</td>
<td><code># this is a note</code></td>
</tr>
<tr class="even">
<td><code>import … as</code></td>
<td>load a library under a nickname</td>
<td><code>import pandas as pd</code></td>
</tr>
<tr class="odd">
<td><code>=</code></td>
<td>store this as</td>
<td><code>x = 5</code></td>
</tr>
<tr class="even">
<td><code>=</code></td>
<td>name an argument, <em>inside</em> a function</td>
<td><code>data=states</code></td>
</tr>
<tr class="odd">
<td><code>()</code></td>
<td>run a function; what it needs goes inside</td>
<td><code>abs(x)</code></td>
</tr>
<tr class="even">
<td><code>,</code></td>
<td>separates one argument from the next</td>
<td><code>plt.hist(x, bins=20)</code></td>
</tr>
<tr class="odd">
<td><code>.</code></td>
<td>belonging to: a library’s function, an object’s method or attribute</td>
<td><code>pd.read_csv</code>, <code>states.shape</code></td>
</tr>
<tr class="even">
<td><code>" "</code></td>
<td>a string: text, taken as-is</td>
<td><code>"data/medicaid.csv"</code></td>
</tr>
<tr class="odd">
<td><code>[" "]</code></td>
<td>pull one column out of a DataFrame</td>
<td><code>states["expanded"]</code></td>
</tr>
<tr class="even">
<td><code>~</code></td>
<td>“broken down by”, inside a model formula</td>
<td><code>"rate ~ expanded"</code></td>
</tr>
<tr class="odd">
<td><code>==</code></td>
<td><em>is</em> equal to: a question, not an instruction</td>
<td><code>year == 2014</code></td>
</tr>
<tr class="even">
<td><code>&gt;=</code> <code>&lt;=</code> <code>&gt;</code> <code>&lt;</code></td>
<td>the usual comparisons</td>
<td><code>diffs &gt;= 64</code></td>
</tr>
<tr class="odd">
<td><code>&amp;</code></td>
<td>and; put each side in its own <code>( )</code></td>
<td><code>x.notna() &amp; (x == 2014)</code></td>
</tr>
<tr class="even">
<td><code>:</code> + indent</td>
<td>the indented lines below belong together</td>
<td>inside the <code>for</code> loop</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p><code>=</code> does both jobs, and you will see both. Python’s style guide writes the first with spaces (<code>x = 5</code>) and the second without (<code>index_col=0</code>). It makes the two jobs visible.</p>
</div>
</section>
<section id="glossary-square-brackets-do-four-jobs" class="slide level2">
<h2>Glossary: square brackets do four jobs</h2>
<p>The one that catches everyone. Same symbol, four different meanings:</p>
<div style="font-size: 0.74em;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td><code>df["col"]</code></td>
<td>pull one <strong>column</strong> out of a table</td>
<td><code>counties["year"]</code></td>
</tr>
<tr class="even">
<td><code>df[test]</code></td>
<td>keep the <strong>rows</strong> where a test is True, in a table or a single column</td>
<td><code>counties[counties["year"] == 2014]</code></td>
</tr>
<tr class="odd">
<td><code>s[label]</code></td>
<td>pick one value by its <strong>label</strong></td>
<td><code>group_means[1]</code></td>
</tr>
<tr class="even">
<td><code>["a", "b"]</code></td>
<td>make a <strong>list</strong>; inside <code>df[ ]</code> it picks several columns</td>
<td><code>[["deaths", "population_20_64"]]</code></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p>If you get a <code>KeyError</code>, read the last line of the message: it names what pandas could not find. It is almost always a column name spelled wrong.</p>
</div>
</section></section>
<section>
<section id="module-2-we-do" class="title-slide slide level1 center">
<h1>Module 2: We do</h1>

</section>
<section id="your-turn-with-a-partner" class="slide level2">
<h2>Your turn, with a partner</h2>
<p>Open <code>scripts/02-we-do.py</code>.</p>
<blockquote>
<p><strong>Do high-poverty states have higher working-age mortality?</strong></p>
</blockquote>
<ul>
<li class="fragment">Same nine steps. Same template. New grouping variable.</li>
<li class="fragment">Where you see <code>______</code>, fill it in.</li>
<li class="fragment"><strong>One types, one reads the code out loud and predicts</strong> what it will do before you run it. Swap at step 5.</li>
<li class="fragment">Stuck two minutes? Red sticky. Don’t burn the module on one blank.</li>
</ul>
</section>
<section id="whats-new-in-module-2" class="slide level2">
<h2>What’s new in Module 2</h2>
<p>Two things you have not seen:</p>
<p><strong>Making groups from a number.</strong> Poverty is continuous, so you split it at the median with <code>np.where()</code>.</p>
<p><strong>A result that runs off the page.</strong> Your red line may sit far out past the whole null distribution. That empty space <em>is</em> the result, not a drawing glitch.</p>
<div class="fragment">
<p>If the p-value line gives you <code>0</code>, that is not p = 0. None of 1000 shuffles got that far, so <strong>report p &lt; 0.001</strong>.</p>
</div>
</section></section>
<section>
<section id="module-3-you-do" class="title-slide slide level1 center">
<h1>Module 3: You do</h1>

</section>
<section id="on-your-own" class="slide level2">
<h2>On your own</h2>
<p>Open <code>scripts/03-they-do.py</code>.</p>
<blockquote>
<p><strong>Do states with above-median unemployment have higher working-age mortality?</strong></p>
</blockquote>
<ul>
<li class="fragment">Nine steps, no code. You have done all nine, twice.</li>
<li class="fragment">Modules 1 and 2 are open in your other tabs. <strong>Use them</strong>.</li>
<li class="fragment">Copying your own working code and changing a variable name is not cheating. It is the job.</li>
<li class="fragment">Step 9 asks you to write the finding in prose. Do that one.</li>
</ul>
</section>
<section id="if-you-finish-early" class="slide level2 scrollable">
<h2>If you finish early</h2>
<ol type="1">
<li class="fragment">Swap the grouping to <code>median_income</code>. Does the story change?</li>
<li class="fragment">You split at the median, which threw information away. Try it continuous: <code>plt.scatter()</code>, then <code>plt.axline()</code> with the slope from <code>smf.ols()</code>. What did the split cost?</li>
<li class="fragment">Put two predictors in one model. Watch what happens to each.</li>
<li class="fragment"><strong>Point today’s script at your own data.</strong> That is the actual goal, and we are here for another twenty minutes.</li>
</ol>
</section></section>
<section>
<section id="where-this-goes" class="title-slide slide level1 center">
<h1>Where this goes</h1>

</section>
<section id="what-today-deliberately-left-out" class="slide level2">
<h2>What today deliberately left out</h2>
<ul>
<li class="fragment"><strong>seaborn</strong> (or <strong>plotnine</strong>, ggplot2 for Python) for nicer plots.</li>
<li class="fragment"><strong>More pandas</strong>: merging, reshaping, method chains, for nicer data wrangling.</li>
<li class="fragment"><strong>Regression properly</strong>: more than one predictor, and what the assumptions buy you.</li>
<li class="fragment"><strong>Quarto</strong>, turning a script into a paper. Two minutes, right now.</li>
</ul>
<div class="fragment">
<p>None of it is a prerequisite for what you did today. You can start Monday with twenty-eight functions and methods.</p>
</div>
</section>
<section id="two-rules-for-your-own-work" class="slide level2">
<h2>Two rules for your own work</h2>
<p><strong>Always open the folder.</strong> Never write <code>os.chdir("/Users/you/...")</code>. It works on exactly one computer, and not for long. Open the project folder and every path in your script stays relative.</p>
<p><strong>Never use <code>%reset</code> to start clean.</strong> It deletes your variables, but libraries stay loaded and any settings you changed stay changed. It does not give you a clean session. Restart Python instead: <strong>Cmd/Ctrl+Shift+0</strong>.</p>
<div class="fragment">
<p>If a script only runs after you have run some <em>other</em> thing first, it isn’t finished.</p>
</div>
</section>
<section id="where-to-get-unstuck" class="slide level2">
<h2>Where to get unstuck</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><code>help(pd.Series.mean)</code></td>
<td>Python’s own help, and it is better than it looks</td>
</tr>
<tr class="even">
<td><strong>StatLab office hours</strong></td>
<td>a human, free, and the fastest option</td>
</tr>
<tr class="odd">
<td>Error message → search</td>
<td>paste the last line verbatim, someone has had it</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Your script from today is the best reference you now own. It works, you typed it, and you know what every line does.</p>
</div>
</section></section>
<section>
<section id="appendix" class="title-slide slide level1 center">
<h1>Appendix</h1>

</section>
<section id="inside-the-quotes-a-path" class="slide level2">
<h2>Inside the quotes: a path</h2>
<div class="anatomy big">
<p><span class="fragment highlight-current-red" data-fragment-index="1">"</span><span class="fragment highlight-current-red" data-fragment-index="2">data/</span><span class="fragment highlight-current-red" data-fragment-index="3">medicaid<span class="fragment highlight-current-red" data-fragment-index="4">.csv</span></span><span class="fragment highlight-current-red" data-fragment-index="1">"</span></p>
</div>
<div class="fragment" data-fragment-index="1">
<p><strong><code>" "</code></strong> make it a <strong>string</strong>: text, taken as-is. Without them, Python reads <code>medicaid</code> as the name of an object, goes looking, and fails.</p>
</div>
<div class="fragment" data-fragment-index="2">
<p><strong><code>data/</code></strong> is a folder. Folder, slash, file: that is a <strong>path</strong>, directions to the file, starting from the folder you opened.</p>
</div>
<div class="fragment" data-fragment-index="3">
<p><strong><code>medicaid.csv</code></strong> is the file itself.</p>
</div>
<div class="fragment" data-fragment-index="4">
<p><strong><code>.csv</code></strong> is the <strong>extension</strong>: what kind of file it is. Comma-separated values, a table saved as plain text. <code>pd.read_csv()</code> reads this kind; an Excel <code>.xlsx</code> needs a different function. Finder and File Explorer hide extensions by default, so you may only see <code>medicaid</code> there.</p>
</div>
</section>
<section id="mac-vs.-windows" class="slide level2">
<h2>Mac vs.&nbsp;Windows</h2>
<p>The full path to the same file, on two laptops:</p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><strong>Mac</strong></td>
<td><code>/Users/you/intro-to-python/data/medicaid.csv</code></td>
</tr>
<tr class="even">
<td><strong>Windows</strong></td>
<td><code>C:\Users\you\intro-to-python\data\medicaid.csv</code></td>
</tr>
</tbody>
</table>
<ul>
<li class="fragment">Ours skips all of that. <code>data/medicaid.csv</code> starts from the folder you opened, so it is the same on every laptop.</li>
<li class="fragment">In Python, always write <code>/</code>, even on Windows. A lone <code>\</code> can silently turn into a special character: in <code>"data\new.csv"</code>, the <code>\n</code> becomes a line break, and Python goes looking for a file that does not exist. <code>/</code> never does that.</li>
</ul>
</section>
<section id="set-up-python-once" class="slide level2 scrollable">
<h2>Set up Python, once</h2>
<p>For anyone who arrives without a working setup. These go in the <strong>Terminal</strong> (<strong>Terminal → New Terminal</strong>), not your script. Copy them from the README; don’t retype them.</p>
<ol type="1">
<li><p>Install <strong>uv</strong>, the tool that sets up Python for you:</p>
<p>Mac:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb52-1"><a href=""></a><span class="ex">curl</span> <span class="at">-LsSf</span> https://astral.sh/uv/install.sh <span class="kw">|</span> <span class="fu">sh</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Windows:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode numberSource powershell number-lines code-with-copy"><code class="sourceCode powershell"><span id="cb53-1"><a href=""></a>powershell <span class="op">-</span>ExecutionPolicy ByPass <span class="op">-</span>c <span class="st">"irm https://astral.sh/uv/install.ps1 | iex"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
<li><p>Close that terminal (the trash-can icon) and open a new one, so it can find uv.</p></li>
<li><p>Run <code>uv sync</code>.</p></li>
<li><p>Pick the <code>.venv</code> Python in the top-right corner, then run <code>scripts/00-check.py</code> (<strong>Cmd/Ctrl+Shift+Enter</strong>). It should end with <code>You're ready.</code></p></li>
</ol>
<p><code>uv sync</code> builds a <code>.venv</code> folder holding pandas, numpy, scipy, statsmodels, and matplotlib, in the versions this workshop was tested with. It downloads Python 3.12 for it if you need one. Already have a different Python, like 3.14? That’s fine: uv leaves it alone.</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="01-python-presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="01-python-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="01-python-presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="01-python-presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="01-python-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="01-python-presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="01-python-presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="01-python-presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="01-python-presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="01-python-presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>